server {
    listen 80;
    server_name voice.aavishailab.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://frontend:3000;
    }
}
